### ISSUE TITLE
有些特征数据是第三方数异步返回的需要怎么处理呢

### ISSUE THREAD

**Issue by youtao531** [skyhackvip/risk_engine#11]
有些特征数据是第三方异步返回的需要怎么处理呢，是否能做到顺序执行减少三方调用？

**Comment by skyhackvip** [comment]
对于三方异步返回的特征数据，有几种处理办法。1、预计算。提前加载计算，然后将特征传入。优点是简单且快，缺点是成本费用。2、执行中断。一般决策引擎不支持中断后再断点继续执行（需要特殊定制且复杂度较高），所以会采取拆分决策流的方式，并由调度系统来做两次调度。

**Comment by youtao531** [comment]
感谢作者回复！明白了。
