### ISSUE TITLE
是从什么考虑需要有这个有yml文件层，直接从db读取到内存中不会更好么

### ISSUE THREAD

**Issue by dnlixiaoxin** [skyhackvip/risk_engine#16]

**Comment by skyhackvip** [comment]
是的，文件是一种管理方式，数据库管理会更好，因为这个开源项目不希望有太多依赖，可以开箱体验，所以用了文件方式，而实际中我们是使用数据库做管理的。PS：目前市面上很多决策引擎或规则引擎仍保留文件管理方式。
