### ISSUE TITLE
recover放到单独的goroutine中了

### ISSUE THREAD

**Issue by doubler1125** [skyhackvip/risk_engine#18]
![image](https://github.com/skyhackvip/risk_engine/assets/87970501/fe517530-970c-46f0-b4f5-17927aaa612d)
这样写此处的recover岂不是永远走不到

**Comment by skyhackvip** [comment]
感谢您的提醒，recover 只能捕获同一个goroutine中的panic，所以这里确实存在问题。我会fix这个bug

**Comment by skyhackvip** [comment]
> ![image](https://private-user-images.githubusercontent.com/87970501/305596593-fe517530-970c-46f0-b4f5-17927aaa612d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NzMyMTUsIm5iZiI6MTcwODU3MjkxNSwicGF0aCI6Ii84Nzk3MDUwMS8zMDU1OTY1OTMtZmU1MTc1MzAtOTcwYy00NmYwLWI0ZjUtMTc5MjdhYWE2MTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDAzMzUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MWViMjM0NWVlOGRkOThiMzg3ZGZlZWE2YjExNTMxNGU0ODgzZGJkMDYyYjUyMjlhN2IyODM5MzFjNTI3MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EVBzpXbboElwh25hUWm2qvadAOidFzjW8dJEIr4fuyQ) 这样写此处的recover岂不是永远走不到

已修复：
https://github.com/skyhackvip/risk_engine/pull/19
